---
language: java
sudo: false

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2

install:
  - cp -r src/main/feature .
  - ls -la . feature src/main
  - mvn clean install -DskipChecks=true -DskipTests=true
  - ls -la target/
